### ISSUE TITLE
Cannot import policy_saver

### ISSUE THREAD

**Issue by DaveOuds** [tensorflow/agents#76]
I'm trying to save my policy after training. 
I tried to look for a way to save the policy in the colabs and examples but I couldn't find anything. (Could you please add an example to one of the examples or add it to the policies colab?)

After reading through the code I found the PolicySaver class (agents/tf_agents/policies/policy_saver.py), but I can't seem to import it.

I copied the import from the policy_saver_test.py:

from tf_agents.policies import policy_saver

ImportError: cannot import name 'policy_saver' from 'tf_agents.policies'

**Comment by samfishman** [comment]
Hi Dave,

There are two ways to save policies.

The first is regular TF "checkpointing", which allows you to reload your training or evaluation job after it stops for whatever reason (e.g. a process crash). See any example script (e.g. agents/dqn/examples/v2/train_eval.py) for how to use checkpointing.

The second is the PolicySaver, which allows you to execute a policy without the code used to generate it. We're still ironing out the details of PolicySaver which is why there isn't great documentation yet. Sorry about that. In the meantime you are free to experiment with it - and we'd love you're feedback!

It looks like the PIP release was out of date, which is why you were unable to import policy_saver. I've updated the package, so if you `pip install --upgrade tf-agents`, it should work now. Let me know if you experience more issues, and apologies for the confusion.

**Comment by DaveOuds** [comment]
Hey Sam,

Thanks for your response!

I just installed the updated package, but it is still not working (same error as before).

I also checked the history of the pip package ( https://pypi.org/project/tf-agents/#history) and it seems the last update was January 17.

**Comment by samfishman** [comment]
Hi Dave,

Oops, I meant to say `pip install --upgrade tf-agents-nightly` rather than `tf-agents`. We are waiting on tensorflow 1.14 to release a stable version of tf-agents (since we rely on a few features not present in 1.13). You'll want to also be sure to install a nightly version of tensorflow (either tf-nightly or tf-nightly-gpu).

**Comment by DaveOuds** [comment]
Hey Sam,

It's working now thanks!
